apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf  # name of ConfigMap, referenced in other files
data:
  host: product-db-service:3333  # host address of mysql server, we are using DNS of Service
  #host: 14.25.33.21:3333  # host address of mysql server, we are using DNS of Service
  name: product # name of the database for application