apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
  - port: 8085
    targetPort: 8085
    name: http
  selector:
    app: product
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: hchetoui/product:1.0
        ports:
        - containerPort: 8085
        env:
        - name: B_HOST
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: name
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DDL
          value: update